version: '3.7'

services:

  db:
    image: postgres:16-alpine
    environment:
      # Create db
      POSTGRES_DB: vertx-big-board
      # Use postgres/secret user/password credentials
      POSTGRES_PASSWORD: postgres
      # enforce UTC timezone
      TZ: UTC
    volumes:
      - vertx-stock-broker-data-local:/var/lib/postgresql/data
    ports:
      - 5431:5431

  adminer:
    image: adminer:4
    ports:
      - 8081:8080

# permanent storage of data.
# > docker volume rm postgres_vertx-stock-broker-data-local
volumes:
  vertx-stock-broker-data-local:
