version: '3.7'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: vertx-big-board
      MYSQL_PASSWORD: root@04
      MYSQL_ROOT_PASSWORD: root@04
    ports:
      - 3306:3307

  adminer:
    image: adminer:4
    restart: always
    ports:
      - 8081:8080
volumes:
  vertx-stock-broker-data-local:
